{
	"options": {
		"TH8Time_ExtendedTimeSystem_Enable": {
			"type": "i8",
			"val": 0
		},
		"TH8Time_LifeBombLimitHUD_Enable": {
			"type": "i8",
			"val": 0
		},
		
		"TH8Time_Zero_Color": { "type": "i32", "val": "0xFFFFFFFF" },
		"TH8Time_First_Color": { "type": "i32", "val": "0xFFFFF0C0" },
		"TH8Time_Second_Color": { "type": "i32", "val": "0xFFFFC0C0" },
		"TH8Time_Zero_Color_Flipped": { "type": "i32", "val": "0xFFFFFFFF" },
		"TH8Time_First_Color_Flipped": { "type": "i32", "val": "0xC0F0FFFF" },
		"TH8Time_Second_Color_Flipped": { "type": "i32", "val": "0xC0C0FFFF" },
		
		"TH8Time_Second_Time_Advance": { "type": "i8", "val": 1 },
		"TH8Time_First_Time_Advance": { "type": "i8", "val": 2 },
		"TH8Time_Zero_Time_Advance": { "type": "i8", "val": 3 },
		"TH8Time_Player_Succ_Advance": { "type": "i8", "val": 4 },
		"TH8Time_Kaguya_Time_Advance": { "type": "i8", "val": 1 },
		
		"TH8Time_Stage1_Easy_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage1_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Normal_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage1_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Hard_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage1_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Lunatic_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage1_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Extra_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage1_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Phantasm_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage1_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_6_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage1_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_7_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage1_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage2_Easy_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage2_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Normal_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage2_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Hard_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage2_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Lunatic_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage2_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Extra_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage2_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Phantasm_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage2_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_6_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage2_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_7_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage2_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage3_Easy_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage3_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Normal_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage3_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Hard_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage3_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Lunatic_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage3_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Extra_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage3_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Phantasm_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage3_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_6_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage3_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_7_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage3_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage4a_Easy_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage4a_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Normal_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage4a_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Hard_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage4a_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Lunatic_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage4a_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Extra_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage4a_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Phantasm_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage4a_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_6_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage4a_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_7_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage4a_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage4b_Easy_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage4b_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Normal_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage4b_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Hard_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage4b_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Lunatic_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage4b_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Extra_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage4b_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Phantasm_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage4b_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_6_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage4b_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_7_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage4b_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage5_Easy_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage5_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Normal_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage5_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Hard_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage5_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Lunatic_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_Stage5_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Extra_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage5_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Phantasm_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage5_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_6_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage5_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_7_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage5_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage6a_Easy_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6a_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Normal_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6a_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Hard_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6a_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Lunatic_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6a_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Extra_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6a_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Phantasm_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6a_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_6_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6a_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_7_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6a_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage6b_Easy_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6b_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Normal_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6b_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Hard_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6b_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Lunatic_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6b_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Extra_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6b_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Phantasm_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6b_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_6_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6b_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_7_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_Stage6b_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_StageEx_Easy_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_StageEx_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Normal_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_StageEx_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Hard_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_StageEx_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Lunatic_Time_Enable": { "type": "i8", "val": 1 },
		"TH8Time_StageEx_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Extra_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_StageEx_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Phantasm_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_StageEx_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_6_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_StageEx_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_7_Time_Enable": { "type": "i8", "val": 0 },
		"TH8Time_StageEx_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_7_Bomb_Limit": { "type": "i8", "val": -1 }
	},
	"codecaves": {
		"TH8Time_ColorTable": "FFFFFFFF // C0F0FFFF // C0C0FFFF",
		"TH8Time_ColorTable_Option": "<option:TH8Time_Zero_Color><option:TH8Time_First_Color><option:TH8Time_Second_Color>",
		"TH8Time_ColorTable_Option_Flipped": "<option:TH8Time_Zero_Color_Flipped><option:TH8Time_First_Color_Flipped><option:TH8Time_Second_Color_Flipped>",
		"TH8Time_TimeEnableTable": "<option:TH8Time_Stage1_Time_Enable><option:TH8Time_Stage2_Time_Enable><option:TH8Time_Stage3_Time_Enable><option:TH8Time_Stage4a_Time_Enable><option:TH8Time_Stage4b_Time_Enable><option:TH8Time_Stage5_Time_Enable><option:TH8Time_Stage6a_Time_Enable><option:TH8Time_Stage6b_Time_Enable><option:TH8Time_StageEx_Time_Enable>",
		
		"TH8Time_Stage1_Easy_Data": "<option:TH8Time_Stage1_Easy_First_Time><option:TH8Time_Stage1_Easy_Second_Time><option:TH8Time_Stage1_Easy_Life_Limit><option:TH8Time_Stage1_Easy_Bomb_Limit>0000<option:TH8Time_Stage1_Easy_Time_Enable>",
		
		
		
		
		
		
		
		"TH8Time_Stage1_First_Time": "<option:TH8Time_Stage1_Easy_First_Time><option:TH8Time_Stage1_Normal_First_Time><option:TH8Time_Stage1_Hard_First_Time><option:TH8Time_Stage1_Lunatic_First_Time><option:TH8Time_Stage1_Extra_First_Time><option:TH8Time_Stage1_Phantasm_First_Time><option:TH8Time_Stage1_6_First_Time><option:TH8Time_Stage1_7_First_Time>",
		"TH8Time_Stage1_Second_Time": "<option:TH8Time_Stage1_Easy_Second_Time><option:TH8Time_Stage1_Normal_Second_Time><option:TH8Time_Stage1_Hard_Second_Time><option:TH8Time_Stage1_Lunatic_Second_Time><option:TH8Time_Stage1_Extra_Second_Time><option:TH8Time_Stage1_Phantasm_Second_Time><option:TH8Time_Stage1_6_Second_Time><option:TH8Time_Stage1_7_Second_Time>",
		
		"TH8Time_Stage1_Stock_Limits": "<option:TH8Time_Stage1_Easy_Bomb_Limit><option:TH8Time_Stage1_Easy_Life_Limit>",
		
		
		"TH8Time_Stage1_Life_Limit": "<option:TH8Time_Stage1_Easy_Life_Limit><option:TH8Time_Stage1_Normal_Life_Limit><option:TH8Time_Stage1_Hard_Life_Limit><option:TH8Time_Stage1_Lunatic_Life_Limit><option:TH8Time_Stage1_Extra_Life_Limit><option:TH8Time_Stage1_Phantasm_Life_Limit><option:TH8Time_Stage1_6_Life_Limit><option:TH8Time_Stage1_7_Life_Limit>",
		"TH8Time_Stage1_Bomb_Limit": "<option:TH8Time_Stage1_Easy_Bomb_Limit><option:TH8Time_Stage1_Normal_Bomb_Limit><option:TH8Time_Stage1_Hard_Bomb_Limit><option:TH8Time_Stage1_Lunatic_Bomb_Limit><option:TH8Time_Stage1_Extra_Bomb_Limit><option:TH8Time_Stage1_Phantasm_Bomb_Limit><option:TH8Time_Stage1_6_Bomb_Limit><option:TH8Time_Stage1_7_Bomb_Limit>",
		"TH8Time_Stage2_First_Time": "<option:TH8Time_Stage2_Easy_First_Time><option:TH8Time_Stage2_Normal_First_Time><option:TH8Time_Stage2_Hard_First_Time><option:TH8Time_Stage2_Lunatic_First_Time><option:TH8Time_Stage2_Extra_First_Time><option:TH8Time_Stage2_Phantasm_First_Time><option:TH8Time_Stage2_6_First_Time><option:TH8Time_Stage2_7_First_Time>",
		"TH8Time_Stage2_Second_Time": "<option:TH8Time_Stage2_Easy_Second_Time><option:TH8Time_Stage2_Normal_Second_Time><option:TH8Time_Stage2_Hard_Second_Time><option:TH8Time_Stage2_Lunatic_Second_Time><option:TH8Time_Stage2_Extra_Second_Time><option:TH8Time_Stage2_Phantasm_Second_Time><option:TH8Time_Stage2_6_Second_Time><option:TH8Time_Stage2_7_Second_Time>",
		"TH8Time_Stage2_Life_Limit": "<option:TH8Time_Stage2_Easy_Life_Limit><option:TH8Time_Stage2_Normal_Life_Limit><option:TH8Time_Stage2_Hard_Life_Limit><option:TH8Time_Stage2_Lunatic_Life_Limit><option:TH8Time_Stage2_Extra_Life_Limit><option:TH8Time_Stage2_Phantasm_Life_Limit><option:TH8Time_Stage2_6_Life_Limit><option:TH8Time_Stage2_7_Life_Limit>",
		"TH8Time_Stage2_Bomb_Limit": "<option:TH8Time_Stage2_Easy_Bomb_Limit><option:TH8Time_Stage2_Normal_Bomb_Limit><option:TH8Time_Stage2_Hard_Bomb_Limit><option:TH8Time_Stage2_Lunatic_Bomb_Limit><option:TH8Time_Stage2_Extra_Bomb_Limit><option:TH8Time_Stage2_Phantasm_Bomb_Limit><option:TH8Time_Stage2_6_Bomb_Limit><option:TH8Time_Stage2_7_Bomb_Limit>",
		"TH8Time_Stage3_First_Time": "<option:TH8Time_Stage3_Easy_First_Time><option:TH8Time_Stage3_Normal_First_Time><option:TH8Time_Stage3_Hard_First_Time><option:TH8Time_Stage3_Lunatic_First_Time><option:TH8Time_Stage3_Extra_First_Time><option:TH8Time_Stage3_Phantasm_First_Time><option:TH8Time_Stage3_6_First_Time><option:TH8Time_Stage3_7_First_Time>",
		"TH8Time_Stage3_Second_Time": "<option:TH8Time_Stage3_Easy_Second_Time><option:TH8Time_Stage3_Normal_Second_Time><option:TH8Time_Stage3_Hard_Second_Time><option:TH8Time_Stage3_Lunatic_Second_Time><option:TH8Time_Stage3_Extra_Second_Time><option:TH8Time_Stage3_Phantasm_Second_Time><option:TH8Time_Stage3_6_Second_Time><option:TH8Time_Stage3_7_Second_Time>",
		"TH8Time_Stage3_Life_Limit": "<option:TH8Time_Stage3_Easy_Life_Limit><option:TH8Time_Stage3_Normal_Life_Limit><option:TH8Time_Stage3_Hard_Life_Limit><option:TH8Time_Stage3_Lunatic_Life_Limit><option:TH8Time_Stage3_Extra_Life_Limit><option:TH8Time_Stage3_Phantasm_Life_Limit><option:TH8Time_Stage3_6_Life_Limit><option:TH8Time_Stage3_7_Life_Limit>",
		"TH8Time_Stage3_Bomb_Limit": "<option:TH8Time_Stage3_Easy_Bomb_Limit><option:TH8Time_Stage3_Normal_Bomb_Limit><option:TH8Time_Stage3_Hard_Bomb_Limit><option:TH8Time_Stage3_Lunatic_Bomb_Limit><option:TH8Time_Stage3_Extra_Bomb_Limit><option:TH8Time_Stage3_Phantasm_Bomb_Limit><option:TH8Time_Stage3_6_Bomb_Limit><option:TH8Time_Stage3_7_Bomb_Limit>",
		"TH8Time_Stage4a_First_Time": "<option:TH8Time_Stage4a_Easy_First_Time><option:TH8Time_Stage4a_Normal_First_Time><option:TH8Time_Stage4a_Hard_First_Time><option:TH8Time_Stage4a_Lunatic_First_Time><option:TH8Time_Stage4a_Extra_First_Time><option:TH8Time_Stage4a_Phantasm_First_Time><option:TH8Time_Stage4a_6_First_Time><option:TH8Time_Stage4a_7_First_Time>",
		"TH8Time_Stage4a_Second_Time": "<option:TH8Time_Stage4a_Easy_Second_Time><option:TH8Time_Stage4a_Normal_Second_Time><option:TH8Time_Stage4a_Hard_Second_Time><option:TH8Time_Stage4a_Lunatic_Second_Time><option:TH8Time_Stage4a_Extra_Second_Time><option:TH8Time_Stage4a_Phantasm_Second_Time><option:TH8Time_Stage4a_6_Second_Time><option:TH8Time_Stage4a_7_Second_Time>",
		"TH8Time_Stage4a_Life_Limit": "<option:TH8Time_Stage4a_Easy_Life_Limit><option:TH8Time_Stage4a_Normal_Life_Limit><option:TH8Time_Stage4a_Hard_Life_Limit><option:TH8Time_Stage4a_Lunatic_Life_Limit><option:TH8Time_Stage4a_Extra_Life_Limit><option:TH8Time_Stage4a_Phantasm_Life_Limit><option:TH8Time_Stage4a_6_Life_Limit><option:TH8Time_Stage4a_7_Life_Limit>",
		"TH8Time_Stage4a_Bomb_Limit": "<option:TH8Time_Stage4a_Easy_Bomb_Limit><option:TH8Time_Stage4a_Normal_Bomb_Limit><option:TH8Time_Stage4a_Hard_Bomb_Limit><option:TH8Time_Stage4a_Lunatic_Bomb_Limit><option:TH8Time_Stage4a_Extra_Bomb_Limit><option:TH8Time_Stage4a_Phantasm_Bomb_Limit><option:TH8Time_Stage4a_6_Bomb_Limit><option:TH8Time_Stage4a_7_Bomb_Limit>",
		"TH8Time_Stage4b_First_Time": "<option:TH8Time_Stage4b_Easy_First_Time><option:TH8Time_Stage4b_Normal_First_Time><option:TH8Time_Stage4b_Hard_First_Time><option:TH8Time_Stage4b_Lunatic_First_Time><option:TH8Time_Stage4b_Extra_First_Time><option:TH8Time_Stage4b_Phantasm_First_Time><option:TH8Time_Stage4b_6_First_Time><option:TH8Time_Stage4b_7_First_Time>",
		"TH8Time_Stage4b_Second_Time": "<option:TH8Time_Stage4b_Easy_Second_Time><option:TH8Time_Stage4b_Normal_Second_Time><option:TH8Time_Stage4b_Hard_Second_Time><option:TH8Time_Stage4b_Lunatic_Second_Time><option:TH8Time_Stage4b_Extra_Second_Time><option:TH8Time_Stage4b_Phantasm_Second_Time><option:TH8Time_Stage4b_6_Second_Time><option:TH8Time_Stage4b_7_Second_Time>",
		"TH8Time_Stage4b_Life_Limit": "<option:TH8Time_Stage4b_Easy_Life_Limit><option:TH8Time_Stage4b_Normal_Life_Limit><option:TH8Time_Stage4b_Hard_Life_Limit><option:TH8Time_Stage4b_Lunatic_Life_Limit><option:TH8Time_Stage4b_Extra_Life_Limit><option:TH8Time_Stage4b_Phantasm_Life_Limit><option:TH8Time_Stage4b_6_Life_Limit><option:TH8Time_Stage4b_7_Life_Limit>",
		"TH8Time_Stage4b_Bomb_Limit": "<option:TH8Time_Stage4b_Easy_Bomb_Limit><option:TH8Time_Stage4b_Normal_Bomb_Limit><option:TH8Time_Stage4b_Hard_Bomb_Limit><option:TH8Time_Stage4b_Lunatic_Bomb_Limit><option:TH8Time_Stage4b_Extra_Bomb_Limit><option:TH8Time_Stage4b_Phantasm_Bomb_Limit><option:TH8Time_Stage4b_6_Bomb_Limit><option:TH8Time_Stage4b_7_Bomb_Limit>",
		"TH8Time_Stage5_First_Time": "<option:TH8Time_Stage5_Easy_First_Time><option:TH8Time_Stage5_Normal_First_Time><option:TH8Time_Stage5_Hard_First_Time><option:TH8Time_Stage5_Lunatic_First_Time><option:TH8Time_Stage5_Extra_First_Time><option:TH8Time_Stage5_Phantasm_First_Time><option:TH8Time_Stage5_6_First_Time><option:TH8Time_Stage5_7_First_Time>",
		"TH8Time_Stage5_Second_Time": "<option:TH8Time_Stage5_Easy_Second_Time><option:TH8Time_Stage5_Normal_Second_Time><option:TH8Time_Stage5_Hard_Second_Time><option:TH8Time_Stage5_Lunatic_Second_Time><option:TH8Time_Stage5_Extra_Second_Time><option:TH8Time_Stage5_Phantasm_Second_Time><option:TH8Time_Stage5_6_Second_Time><option:TH8Time_Stage5_7_Second_Time>",
		"TH8Time_Stage5_Life_Limit": "<option:TH8Time_Stage5_Easy_Life_Limit><option:TH8Time_Stage5_Normal_Life_Limit><option:TH8Time_Stage5_Hard_Life_Limit><option:TH8Time_Stage5_Lunatic_Life_Limit><option:TH8Time_Stage5_Extra_Life_Limit><option:TH8Time_Stage5_Phantasm_Life_Limit><option:TH8Time_Stage5_6_Life_Limit><option:TH8Time_Stage5_7_Life_Limit>",
		"TH8Time_Stage5_Bomb_Limit": "<option:TH8Time_Stage5_Easy_Bomb_Limit><option:TH8Time_Stage5_Normal_Bomb_Limit><option:TH8Time_Stage5_Hard_Bomb_Limit><option:TH8Time_Stage5_Lunatic_Bomb_Limit><option:TH8Time_Stage5_Extra_Bomb_Limit><option:TH8Time_Stage5_Phantasm_Bomb_Limit><option:TH8Time_Stage5_6_Bomb_Limit><option:TH8Time_Stage5_7_Bomb_Limit>",
		"TH8Time_Stage6a_First_Time": "<option:TH8Time_Stage6a_Easy_First_Time><option:TH8Time_Stage6a_Normal_First_Time><option:TH8Time_Stage6a_Hard_First_Time><option:TH8Time_Stage6a_Lunatic_First_Time><option:TH8Time_Stage6a_Extra_First_Time><option:TH8Time_Stage6a_Phantasm_First_Time><option:TH8Time_Stage6a_6_First_Time><option:TH8Time_Stage6a_7_First_Time>",
		"TH8Time_Stage6a_Second_Time": "<option:TH8Time_Stage6a_Easy_Second_Time><option:TH8Time_Stage6a_Normal_Second_Time><option:TH8Time_Stage6a_Hard_Second_Time><option:TH8Time_Stage6a_Lunatic_Second_Time><option:TH8Time_Stage6a_Extra_Second_Time><option:TH8Time_Stage6a_Phantasm_Second_Time><option:TH8Time_Stage6a_6_Second_Time><option:TH8Time_Stage6a_7_Second_Time>",
		"TH8Time_Stage6a_Life_Limit": "<option:TH8Time_Stage6a_Easy_Life_Limit><option:TH8Time_Stage6a_Normal_Life_Limit><option:TH8Time_Stage6a_Hard_Life_Limit><option:TH8Time_Stage6a_Lunatic_Life_Limit><option:TH8Time_Stage6a_Extra_Life_Limit><option:TH8Time_Stage6a_Phantasm_Life_Limit><option:TH8Time_Stage6a_6_Life_Limit><option:TH8Time_Stage6a_7_Life_Limit>",
		"TH8Time_Stage6a_Bomb_Limit": "<option:TH8Time_Stage6a_Easy_Bomb_Limit><option:TH8Time_Stage6a_Normal_Bomb_Limit><option:TH8Time_Stage6a_Hard_Bomb_Limit><option:TH8Time_Stage6a_Lunatic_Bomb_Limit><option:TH8Time_Stage6a_Extra_Bomb_Limit><option:TH8Time_Stage6a_Phantasm_Bomb_Limit><option:TH8Time_Stage6a_6_Bomb_Limit><option:TH8Time_Stage6a_7_Bomb_Limit>",
		"TH8Time_Stage6b_First_Time": "<option:TH8Time_Stage6b_Easy_First_Time><option:TH8Time_Stage6b_Normal_First_Time><option:TH8Time_Stage6b_Hard_First_Time><option:TH8Time_Stage6b_Lunatic_First_Time><option:TH8Time_Stage6b_Extra_First_Time><option:TH8Time_Stage6b_Phantasm_First_Time><option:TH8Time_Stage6b_6_First_Time><option:TH8Time_Stage6b_7_First_Time>",
		"TH8Time_Stage6b_Second_Time": "<option:TH8Time_Stage6b_Easy_Second_Time><option:TH8Time_Stage6b_Normal_Second_Time><option:TH8Time_Stage6b_Hard_Second_Time><option:TH8Time_Stage6b_Lunatic_Second_Time><option:TH8Time_Stage6b_Extra_Second_Time><option:TH8Time_Stage6b_Phantasm_Second_Time><option:TH8Time_Stage6b_6_Second_Time><option:TH8Time_Stage6b_7_Second_Time>",
		"TH8Time_Stage6b_Life_Limit": "<option:TH8Time_Stage6b_Easy_Life_Limit><option:TH8Time_Stage6b_Normal_Life_Limit><option:TH8Time_Stage6b_Hard_Life_Limit><option:TH8Time_Stage6b_Lunatic_Life_Limit><option:TH8Time_Stage6b_Extra_Life_Limit><option:TH8Time_Stage6b_Phantasm_Life_Limit><option:TH8Time_Stage6b_6_Life_Limit><option:TH8Time_Stage6b_7_Life_Limit>",
		"TH8Time_Stage6b_Bomb_Limit": "<option:TH8Time_Stage6b_Easy_Bomb_Limit><option:TH8Time_Stage6b_Normal_Bomb_Limit><option:TH8Time_Stage6b_Hard_Bomb_Limit><option:TH8Time_Stage6b_Lunatic_Bomb_Limit><option:TH8Time_Stage6b_Extra_Bomb_Limit><option:TH8Time_Stage6b_Phantasm_Bomb_Limit><option:TH8Time_Stage6b_6_Bomb_Limit><option:TH8Time_Stage6b_7_Bomb_Limit>",
		"TH8Time_StageEx_First_Time": "<option:TH8Time_StageEx_Easy_First_Time><option:TH8Time_StageEx_Normal_First_Time><option:TH8Time_StageEx_Hard_First_Time><option:TH8Time_StageEx_Lunatic_First_Time><option:TH8Time_StageEx_Extra_First_Time><option:TH8Time_StageEx_Phantasm_First_Time><option:TH8Time_StageEx_6_First_Time><option:TH8Time_StageEx_7_First_Time>",
		"TH8Time_StageEx_Second_Time": "<option:TH8Time_StageEx_Easy_Second_Time><option:TH8Time_StageEx_Normal_Second_Time><option:TH8Time_StageEx_Hard_Second_Time><option:TH8Time_StageEx_Lunatic_Second_Time><option:TH8Time_StageEx_Extra_Second_Time><option:TH8Time_StageEx_Phantasm_Second_Time><option:TH8Time_StageEx_6_Second_Time><option:TH8Time_StageEx_7_Second_Time>",
		"TH8Time_StageEx_Life_Limit": "<option:TH8Time_StageEx_Easy_Life_Limit><option:TH8Time_StageEx_Normal_Life_Limit><option:TH8Time_StageEx_Hard_Life_Limit><option:TH8Time_StageEx_Lunatic_Life_Limit><option:TH8Time_StageEx_Extra_Life_Limit><option:TH8Time_StageEx_Phantasm_Life_Limit><option:TH8Time_StageEx_6_Life_Limit><option:TH8Time_StageEx_7_Life_Limit>",
		"TH8Time_StageEx_Bomb_Limit": "<option:TH8Time_StageEx_Easy_Bomb_Limit><option:TH8Time_StageEx_Normal_Bomb_Limit><option:TH8Time_StageEx_Hard_Bomb_Limit><option:TH8Time_StageEx_Lunatic_Bomb_Limit><option:TH8Time_StageEx_Extra_Bomb_Limit><option:TH8Time_StageEx_Phantasm_Bomb_Limit><option:TH8Time_StageEx_6_Bomb_Limit><option:TH8Time_StageEx_7_Bomb_Limit>"
	}
}