{
	"options": {
		"TH8Time_ExtendedTimeSystem_Enable": {
			"type": "i32",
			"val": false
		},
		"TH8Time_LifeBombLimitHUD_Enable": {
			"type": "i32",
			"val": false
		},
		
		"TH8Time_Zero_Color": { "type": "i32", "val": 0xFFFFFFFF },
		"TH8Time_First_Color": { "type": "i32", "val": 0xFFFFF0C0 },
		"TH8Time_Second_Color": { "type": "i32", "val": 0xFFFFC0C0 },
		
		"TH8Time_Second_Time_Advance": { "type": "i8", "val": 1 },
		"TH8Time_First_Time_Advance": { "type": "i8", "val": 2 },
		"TH8Time_Zero_Time_Advance": { "type": "i8", "val": 3 },
		"TH8Time_Player_Succ_Advance": { "type": "i8", "val": 4 },
		
		"TH8Time_Stage1_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Easy_Second_Time": { "type": "i32", "val": 2000 },
		"TH8Time_Stage1_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Normal_Second_Time": { "type": "i32", "val": 2500 },
		"TH8Time_Stage1_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Hard_Second_Time": { "type": "i32", "val": 2700 },
		"TH8Time_Stage1_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Lunatic_Second_Time": { "type": "i32", "val": 3000 },
		"TH8Time_Stage1_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage1_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage1_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage2_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Easy_Second_Time": { "type": "i32", "val": 6500 },
		"TH8Time_Stage2_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Normal_Second_Time": { "type": "i32", "val": 7200 },
		"TH8Time_Stage2_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Hard_Second_Time": { "type": "i32", "val": 7200 },
		"TH8Time_Stage2_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Lunatic_Second_Time": { "type": "i32", "val": 7200 },
		"TH8Time_Stage2_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage2_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage2_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage3_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Easy_Second_Time": { "type": "i32", "val": 7500 },
		"TH8Time_Stage3_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Normal_Second_Time": { "type": "i32", "val": 8500 },
		"TH8Time_Stage3_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Hard_Second_Time": { "type": "i32", "val": 8800 },
		"TH8Time_Stage3_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Lunatic_Second_Time": { "type": "i32", "val": 8800 },
		"TH8Time_Stage3_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage3_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage3_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage4a_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Easy_Second_Time": { "type": "i32", "val": 9999 },
		"TH8Time_Stage4a_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Normal_Second_Time": { "type": "i32", "val": 9999 },
		"TH8Time_Stage4a_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Hard_Second_Time": { "type": "i32", "val": 9999 },
		"TH8Time_Stage4a_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4a_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4a_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage4b_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Easy_Second_Time": { "type": "i32", "val": 7500 },
		"TH8Time_Stage4b_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Normal_Second_Time": { "type": "i32", "val": 8500 },
		"TH8Time_Stage4b_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Hard_Second_Time": { "type": "i32", "val": 8500 },
		"TH8Time_Stage4b_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Lunatic_Second_Time": { "type": "i32", "val": 8500 },
		"TH8Time_Stage4b_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage4b_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage4b_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage5_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Easy_Second_Time": { "type": "i32", "val": 9999 },
		"TH8Time_Stage5_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Normal_Second_Time": { "type": "i32", "val": 9999 },
		"TH8Time_Stage5_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Hard_Second_Time": { "type": "i32", "val": 9999 },
		"TH8Time_Stage5_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Lunatic_Second_Time": { "type": "i32", "val": 9999 },
		"TH8Time_Stage5_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage5_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage5_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage6a_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6a_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6a_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_Stage6b_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Extra_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_Stage6b_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_Stage6b_7_Bomb_Limit": { "type": "i8", "val": -1 },
		
		"TH8Time_StageEx_Easy_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Easy_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Easy_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Easy_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Normal_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Normal_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Normal_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Normal_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Hard_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Hard_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Hard_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Hard_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Lunatic_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Lunatic_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Lunatic_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Lunatic_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Extra_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Extra_Second_Time": { "type": "i32", "val": 10 },
		"TH8Time_StageEx_Extra_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Extra_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Phantasm_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Phantasm_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_Phantasm_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_Phantasm_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_6_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_6_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_6_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_6_Bomb_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_7_First_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_7_Second_Time": { "type": "i32", "val": 0 },
		"TH8Time_StageEx_7_Life_Limit": { "type": "i8", "val": -1 },
		"TH8Time_StageEx_7_Bomb_Limit": { "type": "i8", "val": -1 }
	},
	"codecaves": {
		"TH8Time_Stage1_First_Time": "<option:TH8Time_Stage1_Easy_First_Time><option:TH8Time_Stage1_Normal_First_Time><option:TH8Time_Stage1_Hard_First_Time><option:TH8Time_Stage1_Lunatic_First_Time><option:TH8Time_Stage1_Extra_First_Time><option:TH8Time_Stage1_Phantasm_First_Time><option:TH8Time_Stage1_6_First_Time><option:TH8Time_Stage1_7_First_Time>",
		"TH8Time_Stage1_Second_Time": "<option:TH8Time_Stage1_Easy_Second_Time><option:TH8Time_Stage1_Normal_Second_Time><option:TH8Time_Stage1_Hard_Second_Time><option:TH8Time_Stage1_Lunatic_Second_Time><option:TH8Time_Stage1_Extra_Second_Time><option:TH8Time_Stage1_Phantasm_Second_Time><option:TH8Time_Stage1_6_Second_Time><option:TH8Time_Stage1_7_Second_Time>",
		"TH8Time_Stage1_Life_Limit": "<option:TH8Time_Stage1_Easy_Life_Limit><option:TH8Time_Stage1_Normal_Life_Limit><option:TH8Time_Stage1_Hard_Life_Limit><option:TH8Time_Stage1_Lunatic_Life_Limit><option:TH8Time_Stage1_Extra_Life_Limit><option:TH8Time_Stage1_Phantasm_Life_Limit><option:TH8Time_Stage1_6_Life_Limit><option:TH8Time_Stage1_7_Life_Limit>",
		"TH8Time_Stage1_Bomb_Limit": "<option:TH8Time_Stage1_Easy_Bomb_Limit><option:TH8Time_Stage1_Normal_Bomb_Limit><option:TH8Time_Stage1_Hard_Bomb_Limit><option:TH8Time_Stage1_Lunatic_Bomb_Limit><option:TH8Time_Stage1_Extra_Bomb_Limit><option:TH8Time_Stage1_Phantasm_Bomb_Limit><option:TH8Time_Stage1_6_Bomb_Limit><option:TH8Time_Stage1_7_Bomb_Limit>",
		"TH8Time_Stage2_First_Time": "<option:TH8Time_Stage2_Easy_First_Time><option:TH8Time_Stage2_Normal_First_Time><option:TH8Time_Stage2_Hard_First_Time><option:TH8Time_Stage2_Lunatic_First_Time><option:TH8Time_Stage2_Extra_First_Time><option:TH8Time_Stage2_Phantasm_First_Time><option:TH8Time_Stage2_6_First_Time><option:TH8Time_Stage2_7_First_Time>",
		"TH8Time_Stage2_Second_Time": "<option:TH8Time_Stage2_Easy_Second_Time><option:TH8Time_Stage2_Normal_Second_Time><option:TH8Time_Stage2_Hard_Second_Time><option:TH8Time_Stage2_Lunatic_Second_Time><option:TH8Time_Stage2_Extra_Second_Time><option:TH8Time_Stage2_Phantasm_Second_Time><option:TH8Time_Stage2_6_Second_Time><option:TH8Time_Stage2_7_Second_Time>",
		"TH8Time_Stage2_Life_Limit": "<option:TH8Time_Stage2_Easy_Life_Limit><option:TH8Time_Stage2_Normal_Life_Limit><option:TH8Time_Stage2_Hard_Life_Limit><option:TH8Time_Stage2_Lunatic_Life_Limit><option:TH8Time_Stage2_Extra_Life_Limit><option:TH8Time_Stage2_Phantasm_Life_Limit><option:TH8Time_Stage2_6_Life_Limit><option:TH8Time_Stage2_7_Life_Limit>",
		"TH8Time_Stage2_Bomb_Limit": "<option:TH8Time_Stage2_Easy_Bomb_Limit><option:TH8Time_Stage2_Normal_Bomb_Limit><option:TH8Time_Stage2_Hard_Bomb_Limit><option:TH8Time_Stage2_Lunatic_Bomb_Limit><option:TH8Time_Stage2_Extra_Bomb_Limit><option:TH8Time_Stage2_Phantasm_Bomb_Limit><option:TH8Time_Stage2_6_Bomb_Limit><option:TH8Time_Stage2_7_Bomb_Limit>",
		"TH8Time_Stage3_First_Time": "<option:TH8Time_Stage3_Easy_First_Time><option:TH8Time_Stage3_Normal_First_Time><option:TH8Time_Stage3_Hard_First_Time><option:TH8Time_Stage3_Lunatic_First_Time><option:TH8Time_Stage3_Extra_First_Time><option:TH8Time_Stage3_Phantasm_First_Time><option:TH8Time_Stage3_6_First_Time><option:TH8Time_Stage3_7_First_Time>",
		"TH8Time_Stage3_Second_Time": "<option:TH8Time_Stage3_Easy_Second_Time><option:TH8Time_Stage3_Normal_Second_Time><option:TH8Time_Stage3_Hard_Second_Time><option:TH8Time_Stage3_Lunatic_Second_Time><option:TH8Time_Stage3_Extra_Second_Time><option:TH8Time_Stage3_Phantasm_Second_Time><option:TH8Time_Stage3_6_Second_Time><option:TH8Time_Stage3_7_Second_Time>",
		"TH8Time_Stage3_Life_Limit": "<option:TH8Time_Stage3_Easy_Life_Limit><option:TH8Time_Stage3_Normal_Life_Limit><option:TH8Time_Stage3_Hard_Life_Limit><option:TH8Time_Stage3_Lunatic_Life_Limit><option:TH8Time_Stage3_Extra_Life_Limit><option:TH8Time_Stage3_Phantasm_Life_Limit><option:TH8Time_Stage3_6_Life_Limit><option:TH8Time_Stage3_7_Life_Limit>",
		"TH8Time_Stage3_Bomb_Limit": "<option:TH8Time_Stage3_Easy_Bomb_Limit><option:TH8Time_Stage3_Normal_Bomb_Limit><option:TH8Time_Stage3_Hard_Bomb_Limit><option:TH8Time_Stage3_Lunatic_Bomb_Limit><option:TH8Time_Stage3_Extra_Bomb_Limit><option:TH8Time_Stage3_Phantasm_Bomb_Limit><option:TH8Time_Stage3_6_Bomb_Limit><option:TH8Time_Stage3_7_Bomb_Limit>",
		"TH8Time_Stage4a_First_Time": "<option:TH8Time_Stage4a_Easy_First_Time><option:TH8Time_Stage4a_Normal_First_Time><option:TH8Time_Stage4a_Hard_First_Time><option:TH8Time_Stage4a_Lunatic_First_Time><option:TH8Time_Stage4a_Extra_First_Time><option:TH8Time_Stage4a_Phantasm_First_Time><option:TH8Time_Stage4a_6_First_Time><option:TH8Time_Stage4a_7_First_Time>",
		"TH8Time_Stage4a_Second_Time": "<option:TH8Time_Stage4a_Easy_Second_Time><option:TH8Time_Stage4a_Normal_Second_Time><option:TH8Time_Stage4a_Hard_Second_Time><option:TH8Time_Stage4a_Lunatic_Second_Time><option:TH8Time_Stage4a_Extra_Second_Time><option:TH8Time_Stage4a_Phantasm_Second_Time><option:TH8Time_Stage4a_6_Second_Time><option:TH8Time_Stage4a_7_Second_Time>",
		"TH8Time_Stage4a_Life_Limit": "<option:TH8Time_Stage4a_Easy_Life_Limit><option:TH8Time_Stage4a_Normal_Life_Limit><option:TH8Time_Stage4a_Hard_Life_Limit><option:TH8Time_Stage4a_Lunatic_Life_Limit><option:TH8Time_Stage4a_Extra_Life_Limit><option:TH8Time_Stage4a_Phantasm_Life_Limit><option:TH8Time_Stage4a_6_Life_Limit><option:TH8Time_Stage4a_7_Life_Limit>",
		"TH8Time_Stage4a_Bomb_Limit": "<option:TH8Time_Stage4a_Easy_Bomb_Limit><option:TH8Time_Stage4a_Normal_Bomb_Limit><option:TH8Time_Stage4a_Hard_Bomb_Limit><option:TH8Time_Stage4a_Lunatic_Bomb_Limit><option:TH8Time_Stage4a_Extra_Bomb_Limit><option:TH8Time_Stage4a_Phantasm_Bomb_Limit><option:TH8Time_Stage4a_6_Bomb_Limit><option:TH8Time_Stage4a_7_Bomb_Limit>",
		"TH8Time_Stage4b_First_Time": "<option:TH8Time_Stage4b_Easy_First_Time><option:TH8Time_Stage4b_Normal_First_Time><option:TH8Time_Stage4b_Hard_First_Time><option:TH8Time_Stage4b_Lunatic_First_Time><option:TH8Time_Stage4b_Extra_First_Time><option:TH8Time_Stage4b_Phantasm_First_Time><option:TH8Time_Stage4b_6_First_Time><option:TH8Time_Stage4b_7_First_Time>",
		"TH8Time_Stage4b_Second_Time": "<option:TH8Time_Stage4b_Easy_Second_Time><option:TH8Time_Stage4b_Normal_Second_Time><option:TH8Time_Stage4b_Hard_Second_Time><option:TH8Time_Stage4b_Lunatic_Second_Time><option:TH8Time_Stage4b_Extra_Second_Time><option:TH8Time_Stage4b_Phantasm_Second_Time><option:TH8Time_Stage4b_6_Second_Time><option:TH8Time_Stage4b_7_Second_Time>",
		"TH8Time_Stage4b_Life_Limit": "<option:TH8Time_Stage4b_Easy_Life_Limit><option:TH8Time_Stage4b_Normal_Life_Limit><option:TH8Time_Stage4b_Hard_Life_Limit><option:TH8Time_Stage4b_Lunatic_Life_Limit><option:TH8Time_Stage4b_Extra_Life_Limit><option:TH8Time_Stage4b_Phantasm_Life_Limit><option:TH8Time_Stage4b_6_Life_Limit><option:TH8Time_Stage4b_7_Life_Limit>",
		"TH8Time_Stage4b_Bomb_Limit": "<option:TH8Time_Stage4b_Easy_Bomb_Limit><option:TH8Time_Stage4b_Normal_Bomb_Limit><option:TH8Time_Stage4b_Hard_Bomb_Limit><option:TH8Time_Stage4b_Lunatic_Bomb_Limit><option:TH8Time_Stage4b_Extra_Bomb_Limit><option:TH8Time_Stage4b_Phantasm_Bomb_Limit><option:TH8Time_Stage4b_6_Bomb_Limit><option:TH8Time_Stage4b_7_Bomb_Limit>",
		"TH8Time_Stage5_First_Time": "<option:TH8Time_Stage5_Easy_First_Time><option:TH8Time_Stage5_Normal_First_Time><option:TH8Time_Stage5_Hard_First_Time><option:TH8Time_Stage5_Lunatic_First_Time><option:TH8Time_Stage5_Extra_First_Time><option:TH8Time_Stage5_Phantasm_First_Time><option:TH8Time_Stage5_6_First_Time><option:TH8Time_Stage5_7_First_Time>",
		"TH8Time_Stage5_Second_Time": "<option:TH8Time_Stage5_Easy_Second_Time><option:TH8Time_Stage5_Normal_Second_Time><option:TH8Time_Stage5_Hard_Second_Time><option:TH8Time_Stage5_Lunatic_Second_Time><option:TH8Time_Stage5_Extra_Second_Time><option:TH8Time_Stage5_Phantasm_Second_Time><option:TH8Time_Stage5_6_Second_Time><option:TH8Time_Stage5_7_Second_Time>",
		"TH8Time_Stage5_Life_Limit": "<option:TH8Time_Stage5_Easy_Life_Limit><option:TH8Time_Stage5_Normal_Life_Limit><option:TH8Time_Stage5_Hard_Life_Limit><option:TH8Time_Stage5_Lunatic_Life_Limit><option:TH8Time_Stage5_Extra_Life_Limit><option:TH8Time_Stage5_Phantasm_Life_Limit><option:TH8Time_Stage5_6_Life_Limit><option:TH8Time_Stage5_7_Life_Limit>",
		"TH8Time_Stage5_Bomb_Limit": "<option:TH8Time_Stage5_Easy_Bomb_Limit><option:TH8Time_Stage5_Normal_Bomb_Limit><option:TH8Time_Stage5_Hard_Bomb_Limit><option:TH8Time_Stage5_Lunatic_Bomb_Limit><option:TH8Time_Stage5_Extra_Bomb_Limit><option:TH8Time_Stage5_Phantasm_Bomb_Limit><option:TH8Time_Stage5_6_Bomb_Limit><option:TH8Time_Stage5_7_Bomb_Limit>",
		"TH8Time_Stage6a_First_Time": "<option:TH8Time_Stage6a_Easy_First_Time><option:TH8Time_Stage6a_Normal_First_Time><option:TH8Time_Stage6a_Hard_First_Time><option:TH8Time_Stage6a_Lunatic_First_Time><option:TH8Time_Stage6a_Extra_First_Time><option:TH8Time_Stage6a_Phantasm_First_Time><option:TH8Time_Stage6a_6_First_Time><option:TH8Time_Stage6a_7_First_Time>",
		"TH8Time_Stage6a_Second_Time": "<option:TH8Time_Stage6a_Easy_Second_Time><option:TH8Time_Stage6a_Normal_Second_Time><option:TH8Time_Stage6a_Hard_Second_Time><option:TH8Time_Stage6a_Lunatic_Second_Time><option:TH8Time_Stage6a_Extra_Second_Time><option:TH8Time_Stage6a_Phantasm_Second_Time><option:TH8Time_Stage6a_6_Second_Time><option:TH8Time_Stage6a_7_Second_Time>",
		"TH8Time_Stage6a_Life_Limit": "<option:TH8Time_Stage6a_Easy_Life_Limit><option:TH8Time_Stage6a_Normal_Life_Limit><option:TH8Time_Stage6a_Hard_Life_Limit><option:TH8Time_Stage6a_Lunatic_Life_Limit><option:TH8Time_Stage6a_Extra_Life_Limit><option:TH8Time_Stage6a_Phantasm_Life_Limit><option:TH8Time_Stage6a_6_Life_Limit><option:TH8Time_Stage6a_7_Life_Limit>",
		"TH8Time_Stage6a_Bomb_Limit": "<option:TH8Time_Stage6a_Easy_Bomb_Limit><option:TH8Time_Stage6a_Normal_Bomb_Limit><option:TH8Time_Stage6a_Hard_Bomb_Limit><option:TH8Time_Stage6a_Lunatic_Bomb_Limit><option:TH8Time_Stage6a_Extra_Bomb_Limit><option:TH8Time_Stage6a_Phantasm_Bomb_Limit><option:TH8Time_Stage6a_6_Bomb_Limit><option:TH8Time_Stage6a_7_Bomb_Limit>",
		"TH8Time_Stage6b_First_Time": "<option:TH8Time_Stage6b_Easy_First_Time><option:TH8Time_Stage6b_Normal_First_Time><option:TH8Time_Stage6b_Hard_First_Time><option:TH8Time_Stage6b_Lunatic_First_Time><option:TH8Time_Stage6b_Extra_First_Time><option:TH8Time_Stage6b_Phantasm_First_Time><option:TH8Time_Stage6b_6_First_Time><option:TH8Time_Stage6b_7_First_Time>",
		"TH8Time_Stage6b_Second_Time": "<option:TH8Time_Stage6b_Easy_Second_Time><option:TH8Time_Stage6b_Normal_Second_Time><option:TH8Time_Stage6b_Hard_Second_Time><option:TH8Time_Stage6b_Lunatic_Second_Time><option:TH8Time_Stage6b_Extra_Second_Time><option:TH8Time_Stage6b_Phantasm_Second_Time><option:TH8Time_Stage6b_6_Second_Time><option:TH8Time_Stage6b_7_Second_Time>",
		"TH8Time_Stage6b_Life_Limit": "<option:TH8Time_Stage6b_Easy_Life_Limit><option:TH8Time_Stage6b_Normal_Life_Limit><option:TH8Time_Stage6b_Hard_Life_Limit><option:TH8Time_Stage6b_Lunatic_Life_Limit><option:TH8Time_Stage6b_Extra_Life_Limit><option:TH8Time_Stage6b_Phantasm_Life_Limit><option:TH8Time_Stage6b_6_Life_Limit><option:TH8Time_Stage6b_7_Life_Limit>",
		"TH8Time_Stage6b_Bomb_Limit": "<option:TH8Time_Stage6b_Easy_Bomb_Limit><option:TH8Time_Stage6b_Normal_Bomb_Limit><option:TH8Time_Stage6b_Hard_Bomb_Limit><option:TH8Time_Stage6b_Lunatic_Bomb_Limit><option:TH8Time_Stage6b_Extra_Bomb_Limit><option:TH8Time_Stage6b_Phantasm_Bomb_Limit><option:TH8Time_Stage6b_6_Bomb_Limit><option:TH8Time_Stage6b_7_Bomb_Limit>",
		"TH8Time_StageEx_First_Time": "<option:TH8Time_StageEx_Easy_First_Time><option:TH8Time_StageEx_Normal_First_Time><option:TH8Time_StageEx_Hard_First_Time><option:TH8Time_StageEx_Lunatic_First_Time><option:TH8Time_StageEx_Extra_First_Time><option:TH8Time_StageEx_Phantasm_First_Time><option:TH8Time_StageEx_6_First_Time><option:TH8Time_StageEx_7_First_Time>",
		"TH8Time_StageEx_Second_Time": "<option:TH8Time_StageEx_Easy_Second_Time><option:TH8Time_StageEx_Normal_Second_Time><option:TH8Time_StageEx_Hard_Second_Time><option:TH8Time_StageEx_Lunatic_Second_Time><option:TH8Time_StageEx_Extra_Second_Time><option:TH8Time_StageEx_Phantasm_Second_Time><option:TH8Time_StageEx_6_Second_Time><option:TH8Time_StageEx_7_Second_Time>",
		"TH8Time_StageEx_Life_Limit": "<option:TH8Time_StageEx_Easy_Life_Limit><option:TH8Time_StageEx_Normal_Life_Limit><option:TH8Time_StageEx_Hard_Life_Limit><option:TH8Time_StageEx_Lunatic_Life_Limit><option:TH8Time_StageEx_Extra_Life_Limit><option:TH8Time_StageEx_Phantasm_Life_Limit><option:TH8Time_StageEx_6_Life_Limit><option:TH8Time_StageEx_7_Life_Limit>",
		"TH8Time_StageEx_Bomb_Limit": "<option:TH8Time_StageEx_Easy_Bomb_Limit><option:TH8Time_StageEx_Normal_Bomb_Limit><option:TH8Time_StageEx_Hard_Bomb_Limit><option:TH8Time_StageEx_Lunatic_Bomb_Limit><option:TH8Time_StageEx_Extra_Bomb_Limit><option:TH8Time_StageEx_Phantasm_Bomb_Limit><option:TH8Time_StageEx_6_Bomb_Limit><option:TH8Time_StageEx_7_Bomb_Limit>"
	},
	"binhacks": {
		"TH8TimeExtendedTrial_TimesRanksTable": {
			"addr": "RxC77F0",
			"code": "D0 07 B8 0B 98 08 E4 0C C4 09 D8 0E C4 09 A0 0F 94 11 64 19 88 13 84 1C 18 15 E8 1C 7C 15 4C 1D 88 13 4C 1D 70 17 34 21 64 19 60 22 90 1A 28 23 58 1B 10 27 4C 1D F8 2A 60 22 E0 2E 1C 25 C8 32 88 13 4C 1D 70 17 34 21 64 19 60 22 90 1A 28 23 58 1B 10 27 4C 1D F8 2A 60 22 E0 2E 1C 25 C8 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0A 00 0A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 10 0C 14 10 0A 20 10 0A 20 10 0A 20 10 0F 10 10 0F 10"
		}
	}
}